### ISSUE TITLE
asm_annotation和buildSrc能合并到一起吗？

### ISSUE THREAD

**Issue by GitJoBo** [lanshifu/PrivacyMethodHooker#1]
感谢大佬的分享，若能合并，如何合并？

**Comment by lanshifu** [comment]
不能合并，
asm_annotation 是提供给业务使用的注解库，需要业务引入，编译期插件会扫描注解做处理；
buildSrc里面是插件逻辑，只会在编译期作用，不会打包到app中的。

源码在手，可以自己做一下封装。

**Comment by GitJoBo** [comment]
好的，感谢
