### ISSUE TITLE
混淆要特殊配置吗？

### ISSUE THREAD

**Issue by GitJoBo** [lanshifu/PrivacyMethodHooker#5]
混淆要特殊配置吗？测试包会拦截，正式包没有拦截

**Comment by lanshifu** [comment]
不用混淆配置，把AbsClassTransformer类的context.isRelease() 代码块注释掉就行了。

/**
 * 提供拦截方法，可以统一过滤不需要hook的类
 */
open class AbsClassTransformer : ClassTransformer {


    fun onCommInterceptor(context: TransformContext, klass: ClassNode): Boolean {
//        "===onCommInterceptor--->$this====${klass.className}===".println()
        if (context.isRelease()) {
            return true
        }
//
//        if (!DoKitExtUtil.dokitPluginSwitchOpen()) {
//            return true
//        }
        //过滤kotlin module-info
        if (klass.className == "module-info") {
            return true
        }

        return false
    }
}
